export const BUSINESS_CATEGORIES = [
  'Restaurant & Dining',
  'Coffee & Beverages',
  'Retail & Shopping',
  'Health & Wellness',
  'Beauty & Salon',
  'Fitness & Sports',
  'Technology',
  'Professional Services',
  'Home & Garden',
  'Flowers & Gifts',
  'Arts & Entertainment',
  'Education & Training',
  'Automotive',
  'Real Estate',
  'Plumber',
  'Electrician',
  'Builder & Construction',
  'Carpenter & Joiner',
  'Painter & Decorator',
  'Roofer',
  'Plasterer',
  'Tiler',
  'Locksmith',
  'Landscaper & Gardener',
  'Heating & Gas Engineer',
  'Handyman',
  'Cleaning Services',
  'Pest Control',
  'Accounting & Tax',
  'Financial Planning & Advice',
  'Insurance',
  'Mortgage & Lending',
  'Wealth Management',
  'Bookkeeping',
  'Banking Services',
  'Solicitor',
  'Family Law',
  'Commercial Law',
  'Immigration Law',
  'Employment Law',
  'Property & Conveyancing',
  'Criminal Law',
  'Wills & Probate',
  'Other',
];
